import React from 'react';
import PageHeader from '../components/PageHeader';
import { Sparkles, ArrowUpRight, ArrowDownRight, Activity } from 'lucide-react';
import { motion } from 'framer-motion';

const AIInsights = () => {
  const insights = [
    {
      id: 1,
      title: "Unusual Traffic Spike Detected",
      description: "Organic search traffic from the EU region increased by 314% over the last 6 hours.",
      type: "anomaly",
      severity: "high",
      confidence: 94,
      action: "Review Regional Analytics"
    },
    {
      id: 2,
      title: "Upsell Opportunity",
      description: "124 'Pro' users have consistently hit their API limits this week. Recommending targeted 'Enterprise' upgrade campaign.",
      type: "growth",
      severity: "medium",
      confidence: 88,
      action: "Create Campaign"
    },
    {
      id: 3,
      title: "Elevated Churn Risk",
      description: "Accounts in the 'Agency' segment are showing a 15% drop in weekly logins. Historically indicates churn within 30 days.",
      type: "risk",
      severity: "high",
      confidence: 91,
      action: "View At-Risk Accounts"
    },
    {
      id: 4,
      title: "Pricing Page Drop-off",
      description: "Users are abandoning the pricing page after expanding the 'Compare Features' table. Layout simplification recommended.",
      type: "market",
      severity: "low",
      confidence: 76,
      action: "Analyze Funnel"
    }
  ];

  const getTypeStyle = (type) => {
    switch(type) {
      case 'anomaly': return 'text-purple-400 bg-purple-500/10 border-purple-500/20';
      case 'growth': return 'text-emerald-400 bg-emerald-500/10 border-emerald-500/20';
      case 'risk': return 'text-red-400 bg-red-500/10 border-red-500/20';
      case 'market': return 'text-blue-400 bg-blue-500/10 border-blue-500/20';
      default: return 'text-gray-400 bg-gray-500/10 border-gray-500/20';
    }
  };

  return (
    <>
      <PageHeader 
        title="AI Insights Center" 
        description="Predictive intelligence across your business generated by the AstralInsight engine." 
        action={<button className="px-4 py-2 bg-business-brand rounded-lg text-sm text-white font-medium hover:bg-purple-600 transition flex items-center gap-2"><Sparkles className="w-4 h-4"/> Rescan Now</button>}
      />

      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        {insights.map((insight, i) => (
          <motion.div 
            key={insight.id}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="bg-[#0A0A12] border border-white/5 rounded-xl p-6 shadow-lg hover:border-white/10 transition group"
          >
            <div className="flex items-start justify-between mb-4">
              <div className={`px-2.5 py-1 rounded-md text-[10px] uppercase tracking-wider font-semibold border ${getTypeStyle(insight.type)}`}>
                {insight.type}
              </div>
              <div className="flex items-center gap-1.5 text-xs text-gray-500">
                <Activity className="w-3.5 h-3.5" />
                Confidence: <span className="text-white font-medium">{insight.confidence}%</span>
              </div>
            </div>
            <h3 className="text-lg font-semibold text-white mb-2 tracking-tight">{insight.title}</h3>
            <p className="text-gray-400 text-sm leading-relaxed mb-6">
              {insight.description}
            </p>
            <div className="pt-4 border-t border-white/5 flex items-center justify-between">
              <span className="text-xs text-gray-500 flex items-center gap-1">Severity: <span className={`w-2 h-2 rounded-full ${insight.severity === 'high' ? 'bg-red-500' : 'bg-yellow-500'}`}></span> <span className="capitalize text-white">{insight.severity}</span></span>
              <button className="text-sm font-medium text-business-brand group-hover:text-purple-400 transition flex items-center gap-1">
                {insight.action} <ArrowUpRight className="w-4 h-4" />
              </button>
            </div>
          </motion.div>
        ))}
      </div>
    </>
  );
};

export default AIInsights;